Durability bump issue  # ODHACK
stellar/stellar-cli pull request #1639
Opened 2024-09-30 22:38 UTC by KoxyG

### What
The issue was related to the required durability when bumping/extending a contract. I removed the durability field from the argument struct in the "soroban-cli/command/key" file. As a result, the durability flag will no longer be required when running the command.

### Why
This change was made to resolve the issue of requiring the durability flag during contract extension. Additionally, I implemented default persistent storage, so the durability flag is no longer necessary.

### Known limitations
There are currently no known limitations.

2024-10-01 21:40 UTC, KoxyG commented
Hi @janewang i saw you  reviewed my  pr. I also saw one check failed. 

Am i missing an installation process?. Also, is there any issue with my pr?

2024-10-01 21:56 UTC, janewang commented
@KoxyG I just kicked off the tests. Some integration tests are failing

2024-10-02 00:36 UTC, leighmcculloch requested changes
Hi @KoxyG, thanks for contributing. 

The durability option needs to be retained. The issue is that it's default value is not functioning.

2024-10-02 02:06 UTC, willemneal commented
I would change this from `clap::ValueEnum` to `Default`, with `#[default]` above `Persistent`. Then change the arg to be an option and not use the clap's default value. Then you can use `.unwrap_or_default()`.  TL;DR don't rely on clap for the default value.

https://github.com/stellar/stellar-cli/blob/aad9be9708037e122e8e9ff09a67a09c26168513/cmd/soroban-cli/src/commands/contract/mod.rs#L162-L168

2024-10-02 02:50 UTC, leighmcculloch commented
@willemneal If the enum is derive `Default`, then it won't be necessary to make the value an `Option<>`.

2024-10-02 08:35 UTC, KoxyG commented
> Hi @KoxyG, thanks for contributing.
> 
> The durability option needs to be retained. The issue is that it's default value is not functioning.

So, should i change it back to the initial state?. The  default value is persistent

2024-10-02 08:41 UTC, KoxyG commented
The initial issue is that, when the command `soroban contract bump --id C... --ledgers-to-expire 1000` is used. It doesn't work unless the --durability persistent is used along side with the command.

2024-10-02 15:57 UTC, willemneal commented
@leighmcculloch @KoxyG, can either of you reproduce the original issue? I updated the tests to rely on a default durability and it is passing: https://github.com/stellar/stellar-cli/pull/1644

2024-10-02 22:46 UTC, KoxyG commented
> @leighmcculloch @KoxyG, can either of you reproduce the original issue? I updated the tests to rely on a default durability and it is passing: #1644

You updated the default durability as  only "persistent"?

2024-10-03 16:58 UTC, willemneal commented
No just updated the tests to test if the default was working: https://github.com/stellar/stellar-cli/pull/1644/files

So I'm questioning if this PR is needed.  If you deploy a contract to testnet and then use extend are you required to use the `--durability`? When I try it locally and in the test linked above the default seems to be working so perhaps this issue was fixed a while ago. It is from last November so my guess is that the default didn't exist then and was added without closing that issue.

2024-10-29 20:57 UTC, KoxyG commented
Hi @janewang I noticed you reviewed my pull request. Do i need to work on anything froom my end?

2025-01-04 18:06 UTC, closed without merging