Render Stellar Events as JSON Instead of Rust Debug Format and Update WASM Path
stellar/stellar-cli pull request #1642
Opened 2024-10-02 02:06 UTC by juandiegocv27

### What

This PR modifies the Stellar events output to render as JSON instead of using the Rust debug format. Additionally, it updates the path in `boilerplate.rs` for including the WASM file.

### Why

The change is being made because developers are more familiar with the JSON format, which provides a standardized way of viewing event data. It aligns with Render events as json in stellar events pretty output instead of as rust debug issue, aiming to improve the readability and usability of the event logs for developers.

- closes: #1615

2024-10-02 02:07 UTC, juandiegocv27 commented
ready for review: @leighmcculloch

2024-10-02 02:54 UTC, leighmcculloch requested changes
Hi @juandiegocv27, thanks for contributing.

See my comments inline.

2024-10-02 02:54 UTC, leighmcculloch commented on cmd/soroban-cli/src/log/event.rs
> +            debug!("{i}: {json}");
This output is part of the logging and it was just recently written to output both the XDR and the JSON in:
- #1600

The issue being addressed by this PR is to change the stdout output of the `stellar contract events` subcommand, not the log output. If you see the original issue the original issue has an example of what the command is to run, and what the output looks like today. It's that output that the issue describes being changed from Rust debug format to JSON.

2024-10-02 18:16 UTC, juandiegocv27 commented
> Hi @juandiegocv27, thanks for contributing.
> 
> 
> 
> See my comments inline.

thank you for the feedback, I'll fix the issues 🫡

2024-10-06 08:47 UTC, juandiegocv27 commented
@leighmcculloch make the changes and implement some new code, please review and let me know

2024-10-06 09:09 UTC, juandiegocv27 commented
tell what to fix to do solve the problem as fast as possible or if its ready to merge

2024-10-08 09:23 UTC, closed without merging