soroban-rpc: Add metrics for JSON RPC handlers
stellar/stellar-cli pull request #603
Opened 2023-04-20 14:55 UTC by tamirms

### What

Add metrics for JSON RPC handlers

### Why

https://github.com/stellar/soroban-tools/issues/496

### Known limitations

N/A

2023-04-20 15:29 UTC, tsachiherman requested changes
Please add a unit test that verify that this work.

2023-04-21 09:45 UTC, 2opremio commented on cmd/soroban-rpc/internal/jsonrpc.go
> +	endpoint      string
I don't think we need this. Can't we use `Request.Method()`?

2023-04-21 09:48 UTC, 2opremio commented on cmd/soroban-rpc/internal/jsonrpc.go
> +	}
Shouldn't the same be done for the generic JSON-RPC `Response.Error()` field?

https://pkg.go.dev/github.com/creachadair/jrpc2#Response.Error

2023-04-21 09:51 UTC, 2opremio commented on cmd/soroban-rpc/internal/jsonrpc.go
> +	}
We may actually want to record the error codes separately

2023-04-24 18:21 UTC, tsachiherman commented on cmd/soroban-rpc/internal/test/metrics_test.go
> +	response, err := http.Get(test.adminURL() + "/metrics")
this is probably ok here, but just fyi, this is usually being done using "path.Join", which would eliminate double `/`, etc.

2023-04-24 18:21 UTC, tsachiherman approved these changes

2023-04-24 19:25 UTC, tsachiherman commented on cmd/soroban-rpc/internal/test/metrics_test.go
> +	response, err := http.Get(test.adminURL() + "/metrics")
sorry - I should have written [`url.JoinPath`](https://pkg.go.dev/net/url@go1.19beta1#JoinPath)

2023-04-24 21:08 UTC, merged